services:
  docs:
    # image: ifood_saas_local_docs
    # container_name: ifood_saas_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - .envs/.local/.django
    volumes:
      - ./backend/docs:/docs:z
      - ./backend/config:/app/config:z
      - ./backend/ifood_saas:/app/ifood_saas:z
    ports:
      - '9000:9000'
    command: /start-docs
