# Generated by Django 5.1.8 on 2025-04-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('corporate_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('_client_id', models.BinaryField(db_column='client_id')),
                ('_client_secret', models.BinaryField(db_column='client_secret')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='customers.customer')),
            ],
        ),
    ]
