# Generated by Django 5.1.8 on 2025-04-16 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_alter_merchant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
